name: allay
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

isar_version: &isar_version 3.1.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  file_picker: ^5.5.0
  flex_color_scheme: ^7.3.1
  isar: *isar_version
  isar_flutter_libs: *isar_version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  isar_generator: *isar_version

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/models/
  fonts:
    - family: MinecraftAE
      fonts:
        - asset: assets/fonts/Minecraft_AE.ttf
