name: allay
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

isar_version: &isar_version 3.1.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  based_list: ^1.0.1
  dio: ^5.3.2
  flutter_displaymode: ^0.6.0
  file_picker: ^5.5.0
  flex_color_scheme: ^7.3.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  intl: ^0.18.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  isar_generator: *isar_version

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/models/
  fonts:
    - family: MinecraftAE
      fonts:
        - asset: assets/fonts/Minecraft_AE.ttf

flutter_intl:
  enabled: true # 启用国际化
  class_name: AllayL10N # 可选的为生成的本地化类设置名称
  arb_dir: lib/l10n
  output_dir: lib/l10n
